version: '3.9'

services:

  backend:

    build:
      context: ./backend  # Path to the backend directory
      dockerfile: Dockerfile

    ports:
      - 8000:8000  # Map host port 8000 to container port 8000

    depends_on:
      - db

    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
    volumes:
      - ./backend:/app/backend  # Mount the backend directory as a volume in the container

  frontend:

    build:
      context: ./frontend  # Path to the frontend directory
      dockerfile: Dockerfile
        
    ports:
      - 3000:3000  # Map host port 3000 to container port 3000

    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
